AWSTemplateFormatVersion: '2010-09-09'
Description: 'Demo Nested Stack'

Parameters:
  Environment:
    Type: String
  Application:
    Type: String
  BucketName:
    Type: String
  LambdaMemory:
    Type: String
    Default: "128"

Resources:
  NestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./lambda.yaml
      Parameters:
        Application: !Ref Application
        Environment: !Ref Environment
        LambdaMemory: !Ref LambdaMemory
        BucketName: !Ref BucketName



