BuildSpec: |
  version: 0.2
  phases:
    install:
      runtime-versions:
        python: ${PYTHON_VERSION}
      commands:
        - echo Entered the install phase...
        - pip install -U .
      finally:
        - echo Leaving install phase...
    pre_build:
      commands:
        - echo Entered the pre_build phase...
        - cfn-cli --version
        - cfn-cli -v -f samples/Simple/DynamoDB/cfn-cli.yml validate
      finally:
        - echo Leaving pre_build phrase..
    build:
      commands:
        - echo Entered the build phase...
        - cfn-cli -v -f samples/Simple/DynamoDB/cfn-cli.yml -s Default.DDB stack deploy
        - cfn-cli -v -f samples/Simple/DynamoDB/cfn-cli.yml -s Default.DDB stack delete -qi
        - cfn-cli -v -f samples/SAM/api_backend -s Production.ApiBackend-Production stack sync
        - cfn-cli -v -f samples/SAM/api_backend -s Production.ApiBackend-Production drift detect
        - cfn-cli -v -f samples/SAM/api_backend -s Production.ApiBackend-Production drift diff
        - cfn-cli -v -f samples/SAM/api_backend -s Production.ApiBackend-Production stack delete -qi
      finally:
        - echo Leaving build phase...
    post_build:
      commands:
        - echo Entered the post_build phase...
      finally:
        - echo Leaving post_build phase...
