AWSTemplateFormatVersion: "2010-09-09"
Description: Cloudformation stack role

Resources:

  StackRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - !Sub cloudformation.${AWS::URLSuffix}
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

Outputs:
  RoleArn:
    Description: Stack role arn
    Value: !GetAtt StackRole.Arn
